name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        configuration: [ Release ]
        runtime-identifier: [ 'win-x64', 'linux-x64' ]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x

    - name: Publish the application
      run: dotnet publish OKP.Core --configuration ${{ matrix.configuration }} --runtime ${{ matrix.runtime-identifier }} --self-contained false

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Package-${{ matrix.runtime-identifier }}-${{ matrix.configuration }}
        path: |
          OKP.Core/bin/${{ matrix.configuration }}/net6.0/${{ matrix.runtime-identifier }}/publish/*

  build-for-macos:
    name: 'Build (Release, osx-universal)'

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET 6.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x

    - name: Publish the application
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
      run: |
        dotnet publish OKP.Core --configuration Release --runtime osx-x64 --self-contained false
        dotnet publish OKP.Core --configuration Release --runtime osx-arm64 --self-contained false
    - name: Glue the binary
      run: |
        mkdir -p OKP.Core/bin/Release/net6.0/osx-universal/publish
        lipo -create OKP.Core/bin/Release/net6.0/osx-x64/publish/OKP.Core OKP.Core/bin/Release/net6.0/osx-arm64/publish/OKP.Core -output OKP.Core/bin/Release/net6.0/osx-universal/publish/OKP.Core
        cp -R OKP.Core/bin/Release/net6.0/osx-x64/publish/config OKP.Core/bin/Release/net6.0/osx-universal/publish/
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: OKP.Core-osx-universal-Release
        path: |
          OKP.Core/bin/Release/net6.0/osx-universal/publish/*
          !OKP.Core/bin/Release/net6.0/osx-universal/publish/*.pdb
